### PR TITLE
chore: bump @vue/composition-api, fix #244

### LINKED ISSUE #244: fix: vue warn toRefs() when using useMeta
**🐛 The bug**
When I use `useMeta`, I get the following warning in dev mode on server side:
toRefs() expects a reactive object but received a plain one.

**🛠️ To reproduce**
1. Write smth like that:
```typescript
import { defineComponent, useMeta } from '@nuxtjs/composition-api'

export default defineComponent({
  setup() {
    useMeta({ title: '234' })
    return () => <div></div>
  },
  head: {}
})

```
2. exec `npm run dev`
3. see in console:
```
ERROR  [Vue warn]: toRefs() expects a reactive object but received a plain one.
```

**🌈 Expected behaviour**
No warnings

**ℹ️ Additional context**

Package versions:
```
"nuxt": "^2.14.5",
"vue": "^2.6.12",
"@nuxtjs/composition-api": "^0.12.5",
```
Nuxt mode is universal

### PR DESCRIPTION
**Pull request by antfu**
fix #244

### CODE REVIEW

**Review by danielroe — DISMISSED** [review]

**Comment by danielroe** [comment]
Thanks @antfu ❤️

**Comment by antfu** [comment]
Any idea why the test fails?

**Comment by danielroe** [comment]
@antfu Looking into it.

**Comment by danielroe** [comment]
@antfu It's erroring because `Vue.set` is now failing on reactive objects:
```ts
const a = reactive({})
Vue.set(a, 'prop', 'value')
```

See https://codesandbox.io/s/wizardly-glitter-v9nd0?file=/pages/index.vue

I'll see if I can remove it from `useMeta` and then we should be good to go.

**Comment by danielroe** [comment]
@antfu - looks good to go from my point of view but I guess the question is whether you regard the changed behaviour of `Vue.set` as a bug or not.

**Review by danielroe — APPROVED** [review]

**Comment by aaronhuisinga** [comment]
Thanks @antfu and @danielroe! Would love to see this merged so we can work out some of the bugs we're still dealing with!

**Comment by antfu** [comment]
@danielroe Bumped the version to beta.16 and changed `Vue.set` to `set` from VCA. You would also want to use `set` instead of `Vue.set` for most of the cases in the future. 😉

**Comment by danielroe** [comment]
Fantastic - thanks so much for this :heart:

**Review by danielroe — DISMISSED** [review]
Fantastic - thanks so much for this :heart:

**Review by danielroe — APPROVED** [review]

**Comment by bissolli** [comment]
Guys, not sure if it is something that we should be concerned of, but after this update I started getting this friendly error:
```bash
 WARN  in ./.nuxt/composition-api/index.js                   friendly-errors 11:08:50

"export '_set' (reexported as 'set') was not found in '@vue/composition-api'
```

**Comment by danielroe** [comment]
This warning should not appear in `v0.13.0`.

**Pull request merged**
