### PR TITLE
create static reference to route in useContext

### PR DESCRIPTION
**Pull request by shaunc**
Currently, `useContext` creates a new reference to the route and its components on every call, which defeats the ability to watch the route. This PR creates a static object, including the route references, and just updates the route value in the reference when called.

### CODE REVIEW

**Comment by danielroe** [comment]
Thanks for your work on this. Could you explain what you mean by watching a route not working?

**Comment by shaunc** [comment]
Before this patch, useContext would generate a new reference object every time it was called, rather than changing the value of a given reference. Thus, if using the router programmatically, anyone `watch`-ing the old route would not get a change event on change of route.

NB -- vis failing tests -- I think that paths like `vm.$route.query` in the computed references may need to be protected -- `vm.$route == undefined ? undefined : vm.$route.query`. I'm not sure if it wouldn't be best to refer the computed references back to the original `route` reference, or even have a watcher here that reset the values of `query` etc based on `route`. I'm a bit of a newbie wrt to the Composition API. If you comment on the details and indicate which direction I should go, I'll be happy to correct.

**Comment by danielroe** [comment]
@shaunc At the moment watching the route should work - see [this e2e test](https://github.com/nuxt-community/composition-api/blob/master/test/e2e/context.ts) and [the fixture page that watches the route](https://github.com/nuxt-community/composition-api/blob/master/test/fixture/pages/context/_slug.vue).

🤔

It would be really helpful to see what you're trying that is triggering a bug. Any chance of a reproduction either via repo or template.nuxtjs.org?

**Comment by shaunc** [comment]
I can try to boil down a test. I would guess that current tests are working because they have a single component. Perhaps you could explain in a sentence or two how it could possibly work now, so I can get my head around it. Suppose I have two components, not nested or otherwise communicating. One watches the "route" and the other triggers a change in it (eg via redirect()). They each have completely different references to the route. The actual ref()s are just recreated if/when there is a sync call, and their values is never changed. How could vue know that the route object the first component is obsolete?

**Comment by danielroe** [comment]
The route object should be updated by vue-router whenever the route changes, which should reactively propagate into the composition API helpers.

Yes, each time you call `useContext`, you'll get a fresh computed property, but it just points to the underlying route object that is managed and updated by `vue-router`. At least, that's how it *should* work - I'd be very grateful for a bug repro if that's not the case for you!

A note: it wouldn't make sense to update the route only when `useContext` is called because we want the object always up-to-date.

**Comment by shaunc** [comment]
Thanks for the explanation. I had thought the "route" objects were immutable descriptions of the current route, rather than something that was managed.

I'm away from my main development computer right now, but will try to see if I can reproduce in a smallish test case when I'm back on Tuesday.

**Comment by danielroe** [comment]
@shaunc Any update/reproduction?

**Pull request closed without merging**
