### PR TITLE
fix: allow custom `globalContext` and `globalNuxt`

### LINKED ISSUE #37: fix: respect `globals.context`
**🐛 The bug**
We currently use `window.__NUXT__` but [this can be customised](https://nuxtjs.org/api/configuration-global-name/#the-globals-property) and we should respect that.

Thanks to @pooledge for pointing this out.

### PR DESCRIPTION
**Pull request by danielroe**
closes #37

### CODE REVIEW

**Comment by KevinNTH** [comment]
Hey @danielroe :)

I might have a regression since I've upgrade to 0.7.3 regarding the `useContext` during pre-rendering with `nuxt generate`.

image

**Comment by danielroe** [comment]
@KevinNTH Odd 🤔 Would you confirm that you have added `nuxt-composition-api` to your `buildModules`?

**Comment by KevinNTH** [comment]
Yes!

```javascript
   /*
   ** Nuxt.js dev-modules
   */
  buildModules: [
    // https://composition-api.now.sh
    'nuxt-composition-api',
    // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/eslint-module',
    // Doc: https://github.com/nuxt-community/nuxt-tailwindcss
    '@nuxtjs/tailwindcss',
   ],
```

**Comment by danielroe** [comment]
@KevinNTH Better luck now with 0.7.4?

**Comment by KevinNTH** [comment]
Yes, it works fine! Thank you!

**Pull request merged**
