### PR TITLE
feat: allow `ssrRef` to work outside of setup

### PR DESCRIPTION
**Pull request by danielroe**
This PR removes the custom prefetching we were doing (via redefinition of `onServerPrefetch`, and instead uses a transparent proxy for the `ssrRef` on server-side to update the state every time it is changed.

see #40

### CODE REVIEW

**Comment by danielroe** [comment]
Would value your thoughts @mathe42. Do we lose anything by doing it this way?

**Comment by mathe42** [comment]
Yes we can not track deep changes.

**Comment by danielroe** [comment]
@mathe42 Yes, of course. Good catch. Thoughts on amended proxy approach?

**Comment by mathe42** [comment]
This will break IE11

**Comment by mathe42** [comment]
I think we can add a option to use Proxies and fallback to the onServerPrefetch stuff.

Outside Setup when Proxies allowed use it else always send state to client...

**Comment by danielroe** [comment]
@mathe42 

> This will break IE11

This code shouldn't be in the client bundle; it's just server-side.

> Outside Setup when Proxies allowed use it else always send state to client...

It should only send state after something is assigned to the proxy. So

```ts
// This shouldn't be sent
const a = ssrRef('init')
// But this now will be
a.value = 'init'

**Comment by mathe42** [comment]
Nice 👍 

Does this mean we need Node Version >= x? => change package.json

**Comment by mathe42** [comment]
Node >= 6.0 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by mathe42** [comment]
Node >= 6.0 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

But nuxt needs later versions:

https://github.com/nuxt/nuxt.js/blob/dev/distributions/nuxt/package.json

**Pull request merged**
