### PR TITLE
fix: include `.d.mts` file for bundler compatibility

### LINKED ISSUE #785: Extend package.json to be compatible with moduleResolution: bundler
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nuxtjs/composition-api@0.33.1` for the project I'm working on.

The patch is related to the newly introduced default [bundler module resolution](https://nuxt.com/blog/v3-10#bundler-module-resolution)n for Nuxt 3 and respectively `nuxt-module-builder`. As we have to support both Nuxt 3 and Nuxt 2 with some of our internal Nuxt modules, we have gotten some build errors during our recent `nuxt@3.10.1` update.

> src/composables/someFile.ts(1,26): error TS7016: Could not find a declaration file for module '@nuxtjs/composition-api'. '/(...)/custom-nuxt-module/node_modules/@nuxtjs/composition-api/dist/runtime/index.mjs' implicitly has an 'any' type.
  There are types at '/(...)/custom-nuxt-module/node_modules/@nuxtjs/composition-api/dist/runtime/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@nuxtjs/composition-api' library may need to update its package.json or typings.
  
  Please let me know if it helps to create a quick pull request with this change or if we need to extend the type definitions to cover more cases.

Here is the diff that solved our problem:

```diff
diff --git a/node_modules/@nuxtjs/composition-api/package.json b/node_modules/@nuxtjs/composition-api/package.json
index cb246ed..6b9b433 100644
--- a/node_modules/@nuxtjs/composition-api/package.json
+++ b/node_modules/@nuxtjs/composition-api/package.json
@@ -19,7 +19,16 @@
   },
   "sideEffects": true,
   "exports": {
-    ".": "./dist/runtime/index.mjs",
+    ".": {
+      "import": {
+        "types": "./dist/runtime/index.d.ts",
+        "default": "./dist/runtime/index.mjs"
+      },
+      "require": {
+        "types": "./dist/runtime/index.d.ts",
+        "default": "./dist/runtime/index.js"
+      }
+    },
     "./module": "./dist/module/index.mjs",
     "./package.json": "./package.json",
     "./dist/babel-plugin": "./dist/babel-plugin/index.js",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by aussieboi**
As mentioned in #785 this is PR that fixes exports for compatibility with moduleResolution: bundeler. 

Let me know if there is anything to add.

closes #785

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Comment by BryceBarbara** [comment]
@danielroe Do you know what the status of this is? I'm facing this issue right now with `"moduleResolution": "Node16",` and `"moduleResolution": "NodeNext",`

**Comment by BryceBarbara** [comment]
I can confirm that your [latest changes](https://github.com/nuxt-community/composition-api/pull/786/commits/b083dbaaa2f039c56d6840a67d0b7653bf9dc714) do solve my issues. :)

When you know, can you tell me know which version this'll be going into?

**Comment by danielroe** [comment]
Fix released in v0.34.0.

**Comment by BryceBarbara** [comment]
Hmm, @danielroe  are you sure the change went out?

Looks like the change may have got lost in the merge. This is what I was expecting to see:
image
And this is what I see:
image

**Comment by danielroe** [comment]
In the end we create an extra declaration file owing to an issue with siroc. Does it not work?

**Comment by danielroe** [comment]
@BryceBarbara Can you provide a reproduction? I can easily revert to a previous version of this PR if I can confirm the issue.

This looks right to me:

https://arethetypeswrong.github.io/?p=@nuxtjs/composition-api@0.34.0

**Comment by BryceBarbara** [comment]
I can't recreate any more due to losing access to the source code in question but I appreciate your follow up! My guess is that the warning the types tool is referring to `⚠️ ESM (dynamic import only)` is probably what was causing me grief.

Also, I love that arethetypeswrong tool! I wish I knew about it sooner!

**Comment by danielroe** [comment]
Let me know if you or anyone else still has a problem (with a minimal reproduction) and I will very happily iterate on this.

**Pull request merged**
