### PR TITLE
docs: fix installation code block

### PR DESCRIPTION
**Pull request by manniL**
* This PR show code blocks for the quick start guide as intended
* It also removes the ordered list as it will restart after code blocks.

## Old 

grafik

## New

grafik

### CODE REVIEW

**Comment by danielroe** [comment]
Good spot - thanks! However, I think this is a regression with `@nuxt/content`. See https://composition-api-hpktby0al.vercel.app/getting-started/setup for working page on 270e5b77408d2d372cdd310552612de13e22618a.

**Comment by manniL** [comment]
> 
> 
> Good spot - thanks! However, I think this is a regression with `@nuxt/content`. See [composition-api-hpktby0al.vercel.app/getting-started/setup](https://composition-api-hpktby0al.vercel.app/getting-started/setup) for working page on [270e5b7](https://github.com/nuxt-community/composition-api/commit/270e5b77408d2d372cdd310552612de13e22618a).

Ohh, good point! 👍
Will open an issue on nuxt/content then.
What would be the best option for the docs for now - downgrading nuxt/content?

**Comment by danielroe** [comment]
@manniL Sorry - I didn't see your comment :laughing: Let's downgrade `@nuxt/content` for now...

**Comment by manniL** [comment]
> 
> 
> @manniL Sorry - I didn't see your comment 😆 Let's downgrade `@nuxt/content` for now...

No worries at all 😋 

Alright! Will close this PR then 👍

**Pull request closed without merging**
